### ISSUE TITLE
Login and useradministration forms (ext4)

### ISSUE THREAD

**Issue by Sogl** [vivid-planet/kwf-app-demo#3]
Hi!

Why this form looks like without having any css styles?
![login](https://cloud.githubusercontent.com/assets/7556290/6774994/de2bbee6-d175-11e4-82fe-2c75afc1199d.JPG)

Also I can't load user administration page - "Loading..."
Code in Acl.php:

``` php
$this->add(new Kwf_Acl_Resource_MenuUrl('kwf_user_users',
            array('text'=>trlKwf('Useradministration'), 'icon'=>'user.png'),
            '/kwf/user/users'));
$this->add(new Zend_Acl_Resource('kwf_user_user'), 'kwf_user_users');
$this->add(new Zend_Acl_Resource('kwf_user_log'), 'kwf_user_users');
$this->add(new Zend_Acl_Resource('kwf_user_comments'), 'kwf_user_users');

$this->allow('admin', 'kwf_user_users');
```

**Comment by nsams** [comment]
there must be errors when loading css, have a look at red entries in developer tools under network

**Comment by Sogl** [comment]
There are no errors in the console.

**Comment by nsams** [comment]
There must be a 500 response visible in Network

**Comment by Sogl** [comment]
Checked now, same situation...

Also after right user login/pass KWF not log-in.

**Comment by nsams** [comment]
I could reproduce :D

I'll take a look

**Comment by nsams** [comment]
Ok, problem is that the app-demo doesn't use a login by default so that dependency is not needed. Add that in dependencies.ini:

```
Admin.dep[] = KwfUserLogin
```
