### ISSUE TITLE
kwfde installation error (ext 4)

### ISSUE THREAD

**Issue by Sogl** [vivid-planet/kwf-app-demo#6]
Throu new installation:
![kwfde](https://cloud.githubusercontent.com/assets/7556290/7536103/b037f18e-f5cf-11e4-955e-961e23e01294.JPG)

After folder create:
![kwfde2](https://cloud.githubusercontent.com/assets/7556290/7536121/f60114e8-f5cf-11e4-91f3-2599ecb6e548.JPG)

**Comment by nsams** [comment]
thank you for reporting this, has been fixed with https://github.com/koala-framework/koala-framework/commit/bd0595dea3a7ebcf7a00448c1da660817a5bd4a7

**Comment by Sogl** [comment]
Now works, thx!
