### ISSUE TITLE
Composer install error (ext5)

### ISSUE THREAD

**Issue by Sogl** [vivid-planet/kwf-app-demo#8]
Hi!

Just tried to check ext5 demo and couldn't install with composer after `composer update`:

```
c:\OpenServer\domains\kwfapp-ext5>composer install
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Generating autoload files

installing npm dependencies in 'C:\OpenServer\domains\kwfapp-ext5/vendor/koala-framework/kwf-deftjs'...
npm WARN EPACKAGEJSON temp-composer-extra-asssets@ No license field.
npm WARN package.json temp-composer-extra-asssets@ No license field.

installing npm dependencies in 'C:\OpenServer\domains\kwfapp-ext5/vendor/koala-framework/kwf-trl-jsparser'...
npm WARN EPACKAGEJSON temp-composer-extra-asssets@ No license field.
npm WARN package.json temp-composer-extra-asssets@ No license field.

installing npm dependencies in 'C:\OpenServer\domains\kwfapp-ext5/vendor/koala-framework/koala-framework'...
npm WARN EPACKAGEJSON temp-composer-extra-asssets@ No license field.
npm WARN package.json temp-composer-extra-asssets@ No license field.

installing bower dependencies...
bower extjs#~6.0.0-640          cached git://github.com/koala-framework/extjs.git#6.0.0-640
bower extjs#~6.0.0-640        validate 6.0.0-640 against git://github.com/koala-framework/extjs.git#~6.0.0-640
bower extjs#5.1.*               cached git://github.com/koala-framework/extjs.git#5.1.1-451
bower extjs#5.1.*             validate 5.1.1-451 against git://github.com/koala-framework/extjs.git#5.1.*
bower                        ECONFLICT Unable to find suitable version for extjs



  [RuntimeException]
  bower install failed



install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-plugins] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--ignore-platform-reqs] [--] [<packages>]...

c:\OpenServer\domains\kwfapp-ext5>
```

How to fix?

**Comment by nsams** [comment]
the extjs 5 version of kwf-app-demo is currently not under active development. we are however working on:
- full port of the whole koala-framework codebase to ext 6 (yes, including auto*)
- a new kwf-app-demo based on ext 6 using mvvm

@kaufmo is currently working on this :+1:

**Comment by Sogl** [comment]
@nsams , Sounds good!

> full port of the whole koala-framework codebase to ext 6 (yes, including auto*)

Can it possible to migrate from ext2.3? Do I need to use latest kwf 3.11/4.0 for it?
Is ext6 support responsive for using with mobile devices?

> a new kwf-app-demo based on ext 6 using mvvm

When the first release is coming out?

**Comment by nsams** [comment]
> > full port of the whole koala-framework codebase to ext 6 (yes, including auto*)
> 
> Can it possible to migrate from ext2.3? Do I need to use latest kwf 3.11/4.0 for it?
> Is ext6 support responsive for using with mobile devices?

yes, the plan is to migrate all ext 2.3 code. And it will be Kwf 5.0 or something...

> > a new kwf-app-demo based on ext 6 using mvvm
> 
> When the first release is coming out?

sorry, I can't give you a date or something so far
